#!/usr/bin/env python3
"""Offline, data-driven animation transition alignment, no source art alteration.

For EVERY source animation frame and each cyclic target (idle/walk/dash), find
the closest target entry pose after both images are rendered at a common root.
The precomputed map lets the Android renderer choose the appropriate visual
phase at transitions without inspecting pixels at runtime.

Game physics, hitbox frames, special/cancel input timing stay authoritative.
"""
import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

ROOT=Path(__file__).resolve().parents[2]
STATES=("IDLE","WALK_FORWARD","WALK_BACK","DASH")
MAPPATH="android/app/src/main/java/com/gamelutagpt/GeneratedSpriteTransitions.java"
VALIDATOR="tools/sprites/clips"


def load(root,character):
    pack=json.loads((root/"characters"/character/"character.json").read_text(encoding="utf-8"))
    clips={d["id"]:d for p in (root/VALIDATOR).glob("*.json")
           for d in (json.loads(p.read_text(encoding="utf-8")),)}
    return pack,clips


def frame_features(image,rect,root_x,root_y):
    """Silhouette+coarse color in aligned, fixed sized clip rooted at the feet."""
    # One anchor convention for all atlases. Crop loose FX when far from body,
    # while preserving normal kicks, raised hands and weapon length.
    root=(145,258)
    canvas=Image.new("RGBA",(320,290))
    canvas.paste(image.crop(rect),(root[0]-root_x,root[1]-root_y))
    pixels=np.asarray(canvas.resize((80,72),Image.Resampling.BILINEAR),dtype=np.float32)/255.
    alpha=pixels[:,:,3]
    # A colored silhouette avoids interpreting unrelated body configurations as equal.
    return np.concatenate((alpha[:,:,None],
        (pixels[:,:,:3]*alpha[:,:,None])*.28),axis=2).reshape(-1)


def read_frames(root,config,frames):
    report=json.loads((root/config["report"]).read_text(encoding="utf-8"))
    l=report.get("packed",report["layout"])
    fw,fh,count,columns=[l[k] for k in ("frameWidth","frameHeight","frameCount","columns")]
    path=root/config["output"]
    with Image.open(path) as img:
        img=img.convert("RGBA")
        if img.size!=(fw*columns,fh*((count+columns-1)//columns)):
            raise ValueError(f"Atlas geometry mismatch: {path}")
        ans={}
        for index in set(frames):
            if index<0 or index>=count: raise ValueError(f"Invalid frame {index} in {path}")
            x,y=(index%columns)*fw,(index//columns)*fh
            ans[index]=frame_features(img,(x,y,x+fw,y+fh),l["rootX"],l["rootY"])
    return ans


def compute(root=ROOT,character="player_base"):
    pack,clips=load(root,character)
    anims=pack["animations"]
    targets={name:a for name,a in anims.items()
             if name in STATES and a["loop"] and a["frames"]}
    # For a target with no timed frames the initial distance phase uses its
    # distancePerFrame. Other animation clocks stay untouched.
    profiles={}
    atlas_cache={}
    def features(state):
        if state not in atlas_cache:
            a=anims[state]
            atlas_cache[state]=read_frames(root,clips[a["atlas"]],a["frames"])
        return atlas_cache[state]
    diagnostics=[]
    for source,anim in anims.items():
        incoming=features(source)
        for target,tanim in targets.items():
            if target==source:continue
            options=np.stack([features(target)[i] for i in tanim["frames"]])
            mapping=[0]*(max(anim["frames"])+1)
            scores=[]
            for index in set(anim["frames"]):
                sample=incoming[index]
                cost=np.abs(options-sample).mean(axis=1)
                best=int(np.argmin(cost))
                mapping[index]=best
                scores.append(float(cost[best]))
            # Preserve arbitrary source atlas frame IDs with a constant-time lookup.
            # The renderer uses the CURRENT displayed frame (not the frame-count
            # position) when a transition interrupts a source clip.
            key=f"{character}|{source}|{target}"
            profiles[key]=mapping
            diagnostics.append({"from":source,"to":target,"framesCompared":len(scores),
                "averageResidual":round(float(np.mean(scores)),5) if scores else 0,
                "maxResidual":round(float(max(scores)),5) if scores else 0})
    return profiles,diagnostics


def java_code(all_maps):
    """Generation is deterministic, Java 8 compatible, and free of extra Android libs."""
    q=json.dumps
    out=[
        "package com.gamelutagpt;",
        "/** Generated by tools/sprites/autonomous_transitions.py.",
        " * All possible transitions into looped IDLE / walk / dash are phase-matched.",
        " * This only changes VISUAL entry frames, never physics or combat frames.",
        " */",
        "final class GeneratedSpriteTransitions {",
        " private GeneratedSpriteTransitions() {}",
        " static int entry(String character,String from,int sourceFrame,String to) {",
        "  if(character==null||from==null||to==null||sourceFrame<0) return 0;",
        "  String key=character+\"|\"+from+\"|\"+to;",
        "  int[] frames=TABLE.get(key);",
        "  return frames==null||sourceFrame>=frames.length?0:frames[sourceFrame];",
        " }",
        " private static final java.util.Map<String,int[]> TABLE=build();",
        " private static java.util.Map<String,int[]> build() {",
        "  java.util.Map<String,int[]> m=new java.util.HashMap<>();",
    ]
    for k in sorted(all_maps):
        out.append("  m.put("+q(k)+",new int[]{"+",".join(map(str,all_maps[k]))+"});")
    out.extend(["  return java.util.Collections.unmodifiableMap(m);"," }","}",""])
    return "\n".join(out)


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--character",default="player_base")
    p.add_argument("--output",default=MAPPATH)
    p.add_argument("--report",default="android/app/build/transition-alignment.json")
    p.add_argument("--check",action="store_true")
    args=p.parse_args()
    mapping,diagnostics=compute(character=args.character)
    code=java_code(mapping)
    target=ROOT/args.output
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8")!=code:
            raise SystemExit("GeneratedSpriteTransitions.java stale: run autonomous_transitions.py")
    else:
        target.parent.mkdir(parents=True,exist_ok=True)
        target.write_text(code,encoding="utf-8")
    report=ROOT/args.report
    report.parent.mkdir(parents=True,exist_ok=True)
    report.write_text(json.dumps({"character":args.character,
            "pairedTransitions":len(diagnostics),"pairs":diagnostics},indent=2)+"\n",
            encoding="utf-8")
    print(f"Transition mapping: {len(diagnostics)} source->loop pairs; "
          f"generated {'checked' if args.check else 'written'}: {target}")


if __name__=="__main__":
    main()
