#!/usr/bin/env python3
"""Compile validated sprite packs transactionally. No runtime JSON or image conversion."""
import argparse
import base64
import json
import hashlib
import math
import re
import shutil
import tempfile
from pathlib import Path
import import_sprites as importer

ROOT = Path(__file__).resolve().parents[2]
JAVA = 'android/app/src/main/java/com/gamelutagpt/'
REQUIRED = {'IDLE','COMBAT','WALK_FORWARD','WALK_BACK','CROUCH','RISE','JUMP','FALL','DASH','BACKDASH','LAND'}

def read(path):
    return json.loads(path.read_text())

def positive(value, name):
    if isinstance(value, bool) or not isinstance(value, (int,float)) or not math.isfinite(value) or value <= 0:
        raise ValueError(f'{name}: expected a positive finite number')

def safe(root, value):
    p = (root / value).resolve()
    if not p.is_relative_to(root.resolve()):
        raise ValueError(f'Path escapes project: {value}')
    return p

def compile_packs(root, results):
    atlases = {cfg['id']:(cfg,report) for cfg,report in results}
    packs = []
    for path in sorted((root / 'characters').glob('*/character.json')):
        pack = read(path)
        if pack.get('schemaVersion') != 1 or not re.fullmatch('[a-z][a-z0-9_]*', pack['id']):
            raise ValueError(f'{path}: unsupported version or invalid id')
        if pack['id'] != path.parent.name or any(p['id'] == pack['id'] for p in packs):
            raise ValueError(f'{path}: id must be unique and match folder')
        profile = read(safe(root / 'tools/sprites/profiles', pack['profile']))
        for key in ('baseFrameWidth','baseFrameHeight','worldScale','standingVisualHeight'):
            positive(profile[key], key)
        animations = pack['animations']
        if REQUIRED - animations.keys():
            raise ValueError(f"{pack['id']}: missing states {sorted(REQUIRED - animations.keys())}")
        for key,a in animations.items():
            if a['atlas'] not in atlases:
                raise ValueError(f'{key}: unknown atlas {a["atlas"]}')
            cfg,report = atlases[a['atlas']]
            if cfg['profile'] != pack['profile']:
                raise ValueError(f'{key}: atlas and character profiles differ')
            frames = a['frames']
            if not frames or any(type(i) is not int or i < 0 or i >= report['layout']['frameCount'] for i in frames):
                raise ValueError(f'{key}: invalid frame index')
            if type(a['loop']) is not bool:
                raise ValueError(f'{key}: loop must be boolean')
            if 'distancePerFrame' in a:
                positive(a['distancePerFrame'], key)
                if not a['loop'] or 'durationsMs' in a:
                    raise ValueError(f'{key}: distance animation must loop and cannot have durations')
            else:
                if len(a['durationsMs']) != len(frames):
                    raise ValueError(f'{key}: one duration per frame is required')
                for d in a['durationsMs']: positive(d, key)
        for binding,m in pack['moves'].items():
            if binding not in ('L','M','H'):
                raise ValueError(f'{binding}: supported standing inputs are L, M, H')
            if m['animation'] not in animations:
                raise ValueError(f'{binding}: unknown animation')
            a = animations[m['animation']]
            if a['loop'] or 'durationsMs' not in a:
                raise ValueError(f'{binding}: attack must be a timed one-shot')
            if not 0 <= m['activeStartMs'] < m['activeEndMs'] <= sum(a['durationsMs']):
                raise ValueError(f'{binding}: active window outside animation')
            positive(m['reach'], binding)
            if type(m['damage']) is not int or m['damage'] <= 0:
                raise ValueError(f'{binding}: damage must be a positive integer')
        if set(pack['moves']) != {'L','M','H'}:
            raise ValueError(f'{pack["id"]}: L, M, H bindings are required')
        pack['_profile'] = profile
        packs.append(pack)
    roster = read(root / 'characters/roster.json')
    ids = {p['id'] for p in packs}
    if roster.get('schemaVersion') != 1 or roster['defaultCharacter'] not in ids or len(roster['team']) != 2 or any(c not in ids for c in roster['team']):
        raise ValueError('Roster requires a known default and two known team slots')
    if roster['defaultCharacter'] != roster['team'][0]:
        raise ValueError('Default character must match initial team slot')
    q = json.dumps
    f = lambda v: f'{float(v):.8f}f'
    lines = ['package com.gamelutagpt;', 'import java.util.*;',
             '/** Generated by build_characters.py. Edit character packs, not this file. */',
             'final class GeneratedCharacters {',
             ' static final String[] TEAM = new String[]{'+','.join(q(v) for v in roster['team'])+'};',
             ' private static final Map<String,CharacterDefinition> ALL = build();',
             ' static CharacterDefinition get(String id) { CharacterDefinition c=ALL.get(id); if(c==null)throw new IllegalArgumentException(id);return c; }',
             ' static CharacterDefinition defaultCharacter() { return get('+q(roster['defaultCharacter'])+'); }',
             ' private static Map<String,CharacterDefinition> build() {',
             ' Map<String,CharacterDefinition> all=new LinkedHashMap<>();']
    for pack in packs:
        lines += [' {', ' Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();',
                  ' Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();']
        for key,a in pack['animations'].items():
            cfg,report = atlases[a['atlas']]; l = report['layout']
            atlas = 'new CharacterDefinition.Atlas('+','.join([q(Path(cfg['output']).stem)]+[str(l[k]) for k in ('frameWidth','frameHeight','rootX','rootY')]+[str(l.get('columns',l['frameCount'])),str(l['frameCount'])])+')'
            lines += [' a.put('+q(key)+',new CharacterDefinition.Animation('+q(key)+','+atlas+',new int[]{'+','.join(map(str,a['frames']))+'},new float[]{'+','.join(f(v/1000) for v in a.get('durationsMs',[]))+'},'+str(a['loop']).lower()+','+f(a.get('distancePerFrame',0))+'));']
        for key,m in pack['moves'].items():
            lines += [' m.put('+q(key)+',new CharacterDefinition.Move(a.get('+q(m['animation'])+'),'+str(m['damage'])+','+f(m['activeStartMs']/1000)+','+f(m['activeEndMs']/1000)+','+f(m['reach'])+'));']
        p=pack['_profile']
        profile='new CharacterVisualProfile('+','.join([q(p['id']),str(p['baseFrameWidth']),str(p['baseFrameHeight']),f(p['preferredRootX']),f(p['preferredRootY']),f(p['worldScale'])])+')'
        lines += [' all.put('+q(pack['id'])+',new CharacterDefinition('+q(pack['id'])+','+q(pack['displayName'])+','+profile+',a,m));',' }']
    lines += [' return Collections.unmodifiableMap(all);',' }','}','']
    (root / JAVA / 'GeneratedCharacters.java').write_text('\n'.join(lines))
    return packs

def build(root=ROOT, check=False):
    # Isolated staging: no partial assets/Java are published if any pack fails.
    with tempfile.TemporaryDirectory(prefix='sprite-build-') as directory:
        stage=Path(directory)
        for folder in ('art/sprites/source','tools/sprites/clips','tools/sprites/profiles','characters'):
            shutil.copytree(root / folder, stage / folder)
        (stage / JAVA).mkdir(parents=True)
        old=(importer.ROOT,importer.PROFILES_DIR,importer.GENERATED_JAVA)
        importer.ROOT=stage;importer.PROFILES_DIR=stage/'tools/sprites/profiles';importer.GENERATED_JAVA=stage/JAVA/'GeneratedSpriteLayouts.java'
        try:
            results=[];outputs=set();ids=set();names=set()
            for path in sorted((stage/'tools/sprites/clips').glob('*.json')):
                cfg=read(path)
                if not re.fullmatch('[a-z][a-z0-9_]*',cfg['id']) or not re.fullmatch('[A-Z][A-Z0-9_]*',cfg['javaName']): raise ValueError('Invalid atlas id/javaName')
                if cfg['id'] in ids or cfg['javaName'] in names: raise ValueError('Duplicate atlas id/javaName')
                ids.add(cfg['id']);names.add(cfg['javaName'])
                safe(stage,cfg['source']);safe(importer.PROFILES_DIR,cfg['profile'])
                for key in ('output','report','preview'):
                    target=cfg[key];safe(stage,target)
                    expected={'output':'android/app/src/main/res/drawable-nodpi/','report':'tools/sprites/reports/','preview':'android/app/build/sprite-review/'}[key]
                    if not target.startswith(expected) or target in outputs: raise ValueError(f'Invalid or duplicate output {target}')
                    outputs.add(target)
                cfg,report=importer.process_clip(path)
                report['provenance']={'pipelineVersion':1,'sha256':{
                    'source':hashlib.sha256((stage/cfg['source']).read_bytes()).hexdigest(),
                    'config':hashlib.sha256(path.read_bytes()).hexdigest(),
                    'profile':hashlib.sha256((importer.PROFILES_DIR/cfg['profile']).read_bytes()).hexdigest()}}
                (stage/cfg['report']).write_text(json.dumps(report,indent=2)+'\n')
                results.append((cfg,report))
            importer.write_generated_java(results)
            packs=compile_packs(stage,results)
            outputs.update((JAVA+'GeneratedSpriteLayouts.java',JAVA+'GeneratedCharacters.java'))
            # Preview embeds atlases; it works offline and never gets packaged in APK.
            payload={'characters':packs,'atlases':{c['id']:{**r['layout'],'image':'data:image/png;base64,'+base64.b64encode((stage/c['output']).read_bytes()).decode()} for c,r in results}}
            preview='android/app/build/sprite-review/index.html'
            (stage/preview).write_text((root/'tools/sprites/preview.html').read_text().replace('__SPRITE_DATA__',json.dumps(payload).replace('<','\\u003c')))
            outputs.add(preview)
            stale=[]
            for rel in sorted(outputs):
                generated=stage/rel; target=root/rel
                if check and '/build/' not in rel:
                    if not target.exists() or target.read_bytes()!=generated.read_bytes(): stale.append(rel)
                else:
                    target.parent.mkdir(parents=True,exist_ok=True)
                    shutil.copyfile(generated,target)
            if stale: raise ValueError('Generated files are stale; run build_characters.py --write:\n'+'\n'.join(stale))
            print(f'Sprite packs PASS: {len(packs)} characters, {len(results)} atlases; preview: {preview}')
        finally:
            importer.ROOT,importer.PROFILES_DIR,importer.GENERATED_JAVA=old

if __name__=='__main__':
    parser=argparse.ArgumentParser();mode=parser.add_mutually_exclusive_group()
    mode.add_argument('--check',action='store_true');mode.add_argument('--write',action='store_true')
    args=parser.parse_args()
    try: build(check=args.check)
    except (ValueError,KeyError,TypeError,OSError) as error: parser.exit(1,f'Sprite build FAILED: {error}\n')
