package com.gamelutagpt;

/** Generated by tools/sprites/import_sprites.py. Do not edit by hand. */
final class GeneratedSpriteLayouts {
    private GeneratedSpriteLayouts() {}

    static final int MONSTER_NPC_PACK_FRAME_WIDTH = 298;
    static final int MONSTER_NPC_PACK_FRAME_HEIGHT = 231;
    static final int MONSTER_NPC_PACK_ROOT_X = 149;
    static final int MONSTER_NPC_PACK_ROOT_Y = 223;
    static final int MONSTER_NPC_PACK_FRAME_COUNT = 16;

    static final int CROUCH_HEAVY_FRAME_WIDTH = 219;
    static final int CROUCH_HEAVY_FRAME_HEIGHT = 282;
    static final int CROUCH_HEAVY_ROOT_X = 106;
    static final int CROUCH_HEAVY_ROOT_Y = 273;
    static final int CROUCH_HEAVY_FRAME_COUNT = 4;

    static final int CROUCH_LIGHT_FRAME_WIDTH = 215;
    static final int CROUCH_LIGHT_FRAME_HEIGHT = 186;
    static final int CROUCH_LIGHT_ROOT_X = 88;
    static final int CROUCH_LIGHT_ROOT_Y = 177;
    static final int CROUCH_LIGHT_FRAME_COUNT = 4;

    static final int CROUCH_MEDIUM_FRAME_WIDTH = 330;
    static final int CROUCH_MEDIUM_FRAME_HEIGHT = 187;
    static final int CROUCH_MEDIUM_ROOT_X = 126;
    static final int CROUCH_MEDIUM_ROOT_Y = 178;
    static final int CROUCH_MEDIUM_FRAME_COUNT = 4;

    static final int DEFENSE_AIR_FRAME_WIDTH = 166;
    static final int DEFENSE_AIR_FRAME_HEIGHT = 243;
    static final int DEFENSE_AIR_ROOT_X = 103;
    static final int DEFENSE_AIR_ROOT_Y = 242;
    static final int DEFENSE_AIR_FRAME_COUNT = 4;

    static final int DEFENSE_CROUCH_FRAME_WIDTH = 200;
    static final int DEFENSE_CROUCH_FRAME_HEIGHT = 184;
    static final int DEFENSE_CROUCH_ROOT_X = 93;
    static final int DEFENSE_CROUCH_ROOT_Y = 176;
    static final int DEFENSE_CROUCH_FRAME_COUNT = 4;

    static final int DEFENSE_STAND_FRAME_WIDTH = 193;
    static final int DEFENSE_STAND_FRAME_HEIGHT = 245;
    static final int DEFENSE_STAND_ROOT_X = 91;
    static final int DEFENSE_STAND_ROOT_Y = 236;
    static final int DEFENSE_STAND_FRAME_COUNT = 4;

    static final int FALL_DOWN_FRAME_WIDTH = 216;
    static final int FALL_DOWN_FRAME_HEIGHT = 176;
    static final int FALL_DOWN_ROOT_X = 108;
    static final int FALL_DOWN_ROOT_Y = 167;
    static final int FALL_DOWN_FRAME_COUNT = 4;

    static final int HEAVY_STRAIGHT_FRAME_WIDTH = 282;
    static final int HEAVY_STRAIGHT_FRAME_HEIGHT = 225;
    static final int HEAVY_STRAIGHT_ROOT_X = 120;
    static final int HEAVY_STRAIGHT_ROOT_Y = 216;
    static final int HEAVY_STRAIGHT_FRAME_COUNT = 9;

    static final int IDLE_FRAME_WIDTH = 190;
    static final int IDLE_FRAME_HEIGHT = 244;
    static final int IDLE_ROOT_X = 95;
    static final int IDLE_ROOT_Y = 234;
    static final int IDLE_FRAME_COUNT = 8;

    static final int JAB_FRAME_WIDTH = 224;
    static final int JAB_FRAME_HEIGHT = 227;
    static final int JAB_ROOT_X = 112;
    static final int JAB_ROOT_Y = 218;
    static final int JAB_FRAME_COUNT = 3;

    static final int JUMP_HEAVY_FRAME_WIDTH = 233;
    static final int JUMP_HEAVY_FRAME_HEIGHT = 283;
    static final int JUMP_HEAVY_ROOT_X = 116;
    static final int JUMP_HEAVY_ROOT_Y = 282;
    static final int JUMP_HEAVY_FRAME_COUNT = 4;

    static final int JUMP_LIGHT_FRAME_WIDTH = 232;
    static final int JUMP_LIGHT_FRAME_HEIGHT = 252;
    static final int JUMP_LIGHT_ROOT_X = 98;
    static final int JUMP_LIGHT_ROOT_Y = 251;
    static final int JUMP_LIGHT_FRAME_COUNT = 4;

    static final int JUMP_MEDIUM_FRAME_WIDTH = 303;
    static final int JUMP_MEDIUM_FRAME_HEIGHT = 247;
    static final int JUMP_MEDIUM_ROOT_X = 140;
    static final int JUMP_MEDIUM_ROOT_Y = 246;
    static final int JUMP_MEDIUM_FRAME_COUNT = 4;

    static final int MEDIUM_KICK_FRAME_WIDTH = 327;
    static final int MEDIUM_KICK_FRAME_HEIGHT = 245;
    static final int MEDIUM_KICK_ROOT_X = 94;
    static final int MEDIUM_KICK_ROOT_Y = 236;
    static final int MEDIUM_KICK_FRAME_COUNT = 3;

    static final int PLAYER_BASE_MISSING_FRAME_WIDTH = 188;
    static final int PLAYER_BASE_MISSING_FRAME_HEIGHT = 223;
    static final int PLAYER_BASE_MISSING_ROOT_X = 96;
    static final int PLAYER_BASE_MISSING_ROOT_Y = 213;
    static final int PLAYER_BASE_MISSING_FRAME_COUNT = 3;

    static final int MOVEMENT_FRAME_WIDTH = 253;
    static final int MOVEMENT_FRAME_HEIGHT = 229;
    static final int MOVEMENT_ROOT_X = 125;
    static final int MOVEMENT_ROOT_Y = 220;
    static final int MOVEMENT_FRAME_COUNT = 16;

    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_WIDTH = 232;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_HEIGHT = 239;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_X = 105;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_Y = 230;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_COUNT = 9;

    static final int PLAYER_TWO_IDLE_FRAME_WIDTH = 170;
    static final int PLAYER_TWO_IDLE_FRAME_HEIGHT = 244;
    static final int PLAYER_TWO_IDLE_ROOT_X = 85;
    static final int PLAYER_TWO_IDLE_ROOT_Y = 235;
    static final int PLAYER_TWO_IDLE_FRAME_COUNT = 8;

    static final int PLAYER_TWO_JAB_FRAME_WIDTH = 242;
    static final int PLAYER_TWO_JAB_FRAME_HEIGHT = 238;
    static final int PLAYER_TWO_JAB_ROOT_X = 108;
    static final int PLAYER_TWO_JAB_ROOT_Y = 229;
    static final int PLAYER_TWO_JAB_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_WIDTH = 314;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_HEIGHT = 246;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_X = 94;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_Y = 237;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MOVEMENT_FRAME_WIDTH = 244;
    static final int PLAYER_TWO_MOVEMENT_FRAME_HEIGHT = 244;
    static final int PLAYER_TWO_MOVEMENT_ROOT_X = 120;
    static final int PLAYER_TWO_MOVEMENT_ROOT_Y = 235;
    static final int PLAYER_TWO_MOVEMENT_FRAME_COUNT = 16;

}
