package com.gamelutagpt;

/** Generated by tools/sprites/import_sprites.py. Do not edit by hand. */
final class GeneratedSpriteLayouts {
    private GeneratedSpriteLayouts() {}

    static final int MONSTER_NPC_PACK_FRAME_WIDTH = 298;
    static final int MONSTER_NPC_PACK_FRAME_HEIGHT = 231;
    static final int MONSTER_NPC_PACK_ROOT_X = 149;
    static final int MONSTER_NPC_PACK_ROOT_Y = 223;
    static final int MONSTER_NPC_PACK_FRAME_COUNT = 16;

    static final int P03_BACKDASH_FRAME_WIDTH = 184;
    static final int P03_BACKDASH_FRAME_HEIGHT = 249;
    static final int P03_BACKDASH_ROOT_X = 97;
    static final int P03_BACKDASH_ROOT_Y = 237;
    static final int P03_BACKDASH_FRAME_COUNT = 10;

    static final int P03_CROUCH_FRAME_WIDTH = 181;
    static final int P03_CROUCH_FRAME_HEIGHT = 244;
    static final int P03_CROUCH_ROOT_X = 97;
    static final int P03_CROUCH_ROOT_Y = 232;
    static final int P03_CROUCH_FRAME_COUNT = 8;

    static final int P03_DASH_FRAME_WIDTH = 278;
    static final int P03_DASH_FRAME_HEIGHT = 186;
    static final int P03_DASH_ROOT_X = 180;
    static final int P03_DASH_ROOT_Y = 175;
    static final int P03_DASH_FRAME_COUNT = 6;

    static final int P03_FALL_FRAME_WIDTH = 165;
    static final int P03_FALL_FRAME_HEIGHT = 280;
    static final int P03_FALL_ROOT_X = 85;
    static final int P03_FALL_ROOT_Y = 268;
    static final int P03_FALL_FRAME_COUNT = 6;

    static final int P03_HEAVY_FRAME_WIDTH = 312;
    static final int P03_HEAVY_FRAME_HEIGHT = 277;
    static final int P03_HEAVY_ROOT_X = 160;
    static final int P03_HEAVY_ROOT_Y = 259;
    static final int P03_HEAVY_FRAME_COUNT = 23;

    static final int P03_IDLE_FRAME_WIDTH = 191;
    static final int P03_IDLE_FRAME_HEIGHT = 246;
    static final int P03_IDLE_ROOT_X = 75;
    static final int P03_IDLE_ROOT_Y = 235;
    static final int P03_IDLE_FRAME_COUNT = 60;

    static final int P03_JAB_FRAME_WIDTH = 229;
    static final int P03_JAB_FRAME_HEIGHT = 250;
    static final int P03_JAB_ROOT_X = 93;
    static final int P03_JAB_ROOT_Y = 234;
    static final int P03_JAB_FRAME_COUNT = 11;

    static final int P03_JUMP_FRAME_WIDTH = 164;
    static final int P03_JUMP_FRAME_HEIGHT = 281;
    static final int P03_JUMP_ROOT_X = 84;
    static final int P03_JUMP_ROOT_Y = 269;
    static final int P03_JUMP_FRAME_COUNT = 6;

    static final int P03_LAND_FRAME_WIDTH = 165;
    static final int P03_LAND_FRAME_HEIGHT = 256;
    static final int P03_LAND_ROOT_X = 80;
    static final int P03_LAND_ROOT_Y = 244;
    static final int P03_LAND_FRAME_COUNT = 4;

    static final int P03_MEDIUM_FRAME_WIDTH = 217;
    static final int P03_MEDIUM_FRAME_HEIGHT = 249;
    static final int P03_MEDIUM_ROOT_X = 107;
    static final int P03_MEDIUM_ROOT_Y = 235;
    static final int P03_MEDIUM_FRAME_COUNT = 14;

    static final int P03_RISE_FRAME_WIDTH = 184;
    static final int P03_RISE_FRAME_HEIGHT = 251;
    static final int P03_RISE_ROOT_X = 96;
    static final int P03_RISE_ROOT_Y = 238;
    static final int P03_RISE_FRAME_COUNT = 6;

    static final int P03_WALK_BACK_FRAME_WIDTH = 176;
    static final int P03_WALK_BACK_FRAME_HEIGHT = 247;
    static final int P03_WALK_BACK_ROOT_X = 88;
    static final int P03_WALK_BACK_ROOT_Y = 236;
    static final int P03_WALK_BACK_FRAME_COUNT = 19;

    static final int P03_WALK_FORWARD_FRAME_WIDTH = 168;
    static final int P03_WALK_FORWARD_FRAME_HEIGHT = 247;
    static final int P03_WALK_FORWARD_ROOT_X = 82;
    static final int P03_WALK_FORWARD_ROOT_Y = 235;
    static final int P03_WALK_FORWARD_FRAME_COUNT = 36;

    static final int BACKDASH_SET_FRAME_WIDTH = 256;
    static final int BACKDASH_SET_FRAME_HEIGHT = 248;
    static final int BACKDASH_SET_ROOT_X = 106;
    static final int BACKDASH_SET_ROOT_Y = 237;
    static final int BACKDASH_SET_FRAME_COUNT = 10;

    static final int CROUCH_SET_FRAME_WIDTH = 194;
    static final int CROUCH_SET_FRAME_HEIGHT = 245;
    static final int CROUCH_SET_ROOT_X = 101;
    static final int CROUCH_SET_ROOT_Y = 234;
    static final int CROUCH_SET_FRAME_COUNT = 8;

    static final int CROUCH_HEAVY_FRAME_WIDTH = 196;
    static final int CROUCH_HEAVY_FRAME_HEIGHT = 352;
    static final int CROUCH_HEAVY_ROOT_X = 95;
    static final int CROUCH_HEAVY_ROOT_Y = 334;
    static final int CROUCH_HEAVY_FRAME_COUNT = 12;

    static final int CROUCH_LIGHT_FRAME_WIDTH = 241;
    static final int CROUCH_LIGHT_FRAME_HEIGHT = 195;
    static final int CROUCH_LIGHT_ROOT_X = 93;
    static final int CROUCH_LIGHT_ROOT_Y = 183;
    static final int CROUCH_LIGHT_FRAME_COUNT = 11;

    static final int CROUCH_MEDIUM_FRAME_WIDTH = 342;
    static final int CROUCH_MEDIUM_FRAME_HEIGHT = 182;
    static final int CROUCH_MEDIUM_ROOT_X = 184;
    static final int CROUCH_MEDIUM_ROOT_Y = 172;
    static final int CROUCH_MEDIUM_FRAME_COUNT = 16;

    static final int DASH_SET_FRAME_WIDTH = 290;
    static final int DASH_SET_FRAME_HEIGHT = 157;
    static final int DASH_SET_ROOT_X = 186;
    static final int DASH_SET_ROOT_Y = 145;
    static final int DASH_SET_FRAME_COUNT = 6;

    static final int DEFEAT_FRAME_WIDTH = 159;
    static final int DEFEAT_FRAME_HEIGHT = 256;
    static final int DEFEAT_ROOT_X = 85;
    static final int DEFEAT_ROOT_Y = 242;
    static final int DEFEAT_FRAME_COUNT = 33;

    static final int DEFENSE_AIR_FRAME_WIDTH = 172;
    static final int DEFENSE_AIR_FRAME_HEIGHT = 243;
    static final int DEFENSE_AIR_ROOT_X = 84;
    static final int DEFENSE_AIR_ROOT_Y = 232;
    static final int DEFENSE_AIR_FRAME_COUNT = 6;

    static final int DEFENSE_CROUCH_FRAME_WIDTH = 188;
    static final int DEFENSE_CROUCH_FRAME_HEIGHT = 199;
    static final int DEFENSE_CROUCH_ROOT_X = 89;
    static final int DEFENSE_CROUCH_ROOT_Y = 188;
    static final int DEFENSE_CROUCH_FRAME_COUNT = 6;

    static final int DEFENSE_STAND_FRAME_WIDTH = 194;
    static final int DEFENSE_STAND_FRAME_HEIGHT = 242;
    static final int DEFENSE_STAND_ROOT_X = 106;
    static final int DEFENSE_STAND_ROOT_Y = 230;
    static final int DEFENSE_STAND_FRAME_COUNT = 8;

    static final int ENERGY_SET_FRAME_WIDTH = 235;
    static final int ENERGY_SET_FRAME_HEIGHT = 249;
    static final int ENERGY_SET_ROOT_X = 98;
    static final int ENERGY_SET_ROOT_Y = 238;
    static final int ENERGY_SET_FRAME_COUNT = 11;

    static final int FALL_DOWN_FRAME_WIDTH = 320;
    static final int FALL_DOWN_FRAME_HEIGHT = 218;
    static final int FALL_DOWN_ROOT_X = 169;
    static final int FALL_DOWN_ROOT_Y = 206;
    static final int FALL_DOWN_FRAME_COUNT = 11;

    static final int FALL_AIR_SET_FRAME_WIDTH = 171;
    static final int FALL_AIR_SET_FRAME_HEIGHT = 274;
    static final int FALL_AIR_SET_ROOT_X = 91;
    static final int FALL_AIR_SET_ROOT_Y = 262;
    static final int FALL_AIR_SET_FRAME_COUNT = 6;

    static final int GETUP_SET_FRAME_WIDTH = 308;
    static final int GETUP_SET_FRAME_HEIGHT = 246;
    static final int GETUP_SET_ROOT_X = 156;
    static final int GETUP_SET_ROOT_Y = 235;
    static final int GETUP_SET_FRAME_COUNT = 12;

    static final int HEAVY_STRAIGHT_FRAME_WIDTH = 292;
    static final int HEAVY_STRAIGHT_FRAME_HEIGHT = 248;
    static final int HEAVY_STRAIGHT_ROOT_X = 110;
    static final int HEAVY_STRAIGHT_ROOT_Y = 237;
    static final int HEAVY_STRAIGHT_FRAME_COUNT = 23;

    static final int HIT_AIR_SET_FRAME_WIDTH = 227;
    static final int HIT_AIR_SET_FRAME_HEIGHT = 277;
    static final int HIT_AIR_SET_ROOT_X = 118;
    static final int HIT_AIR_SET_ROOT_Y = 265;
    static final int HIT_AIR_SET_FRAME_COUNT = 4;

    static final int HIT_CROUCH_FRAME_WIDTH = 232;
    static final int HIT_CROUCH_FRAME_HEIGHT = 206;
    static final int HIT_CROUCH_ROOT_X = 95;
    static final int HIT_CROUCH_ROOT_Y = 195;
    static final int HIT_CROUCH_FRAME_COUNT = 9;

    static final int HIT_STAND_FRAME_WIDTH = 213;
    static final int HIT_STAND_FRAME_HEIGHT = 269;
    static final int HIT_STAND_ROOT_X = 95;
    static final int HIT_STAND_ROOT_Y = 254;
    static final int HIT_STAND_FRAME_COUNT = 9;

    static final int IDLE_FRAME_WIDTH = 173;
    static final int IDLE_FRAME_HEIGHT = 245;
    static final int IDLE_ROOT_X = 86;
    static final int IDLE_ROOT_Y = 235;
    static final int IDLE_FRAME_COUNT = 76;

    static final int INTRO_SET_FRAME_WIDTH = 181;
    static final int INTRO_SET_FRAME_HEIGHT = 292;
    static final int INTRO_SET_ROOT_X = 84;
    static final int INTRO_SET_ROOT_Y = 279;
    static final int INTRO_SET_FRAME_COUNT = 27;

    static final int JAB_FRAME_WIDTH = 231;
    static final int JAB_FRAME_HEIGHT = 244;
    static final int JAB_ROOT_X = 94;
    static final int JAB_ROOT_Y = 232;
    static final int JAB_FRAME_COUNT = 11;

    static final int JUMP_SET_FRAME_WIDTH = 171;
    static final int JUMP_SET_FRAME_HEIGHT = 274;
    static final int JUMP_SET_ROOT_X = 90;
    static final int JUMP_SET_ROOT_Y = 262;
    static final int JUMP_SET_FRAME_COUNT = 6;

    static final int JUMP_HEAVY_FRAME_WIDTH = 278;
    static final int JUMP_HEAVY_FRAME_HEIGHT = 270;
    static final int JUMP_HEAVY_ROOT_X = 109;
    static final int JUMP_HEAVY_ROOT_Y = 259;
    static final int JUMP_HEAVY_FRAME_COUNT = 7;

    static final int JUMP_HEAVY_DOWN_FRAME_WIDTH = 214;
    static final int JUMP_HEAVY_DOWN_FRAME_HEIGHT = 207;
    static final int JUMP_HEAVY_DOWN_ROOT_X = 104;
    static final int JUMP_HEAVY_DOWN_ROOT_Y = 195;
    static final int JUMP_HEAVY_DOWN_FRAME_COUNT = 7;

    static final int JUMP_LIGHT_FRAME_WIDTH = 254;
    static final int JUMP_LIGHT_FRAME_HEIGHT = 206;
    static final int JUMP_LIGHT_ROOT_X = 90;
    static final int JUMP_LIGHT_ROOT_Y = 195;
    static final int JUMP_LIGHT_FRAME_COUNT = 7;

    static final int JUMP_MEDIUM_FRAME_WIDTH = 282;
    static final int JUMP_MEDIUM_FRAME_HEIGHT = 286;
    static final int JUMP_MEDIUM_ROOT_X = 88;
    static final int JUMP_MEDIUM_ROOT_Y = 274;
    static final int JUMP_MEDIUM_FRAME_COUNT = 7;

    static final int LAND_SET_FRAME_WIDTH = 176;
    static final int LAND_SET_FRAME_HEIGHT = 244;
    static final int LAND_SET_ROOT_X = 93;
    static final int LAND_SET_ROOT_Y = 232;
    static final int LAND_SET_FRAME_COUNT = 4;

    static final int MEDIUM_KICK_FRAME_WIDTH = 237;
    static final int MEDIUM_KICK_FRAME_HEIGHT = 244;
    static final int MEDIUM_KICK_ROOT_X = 98;
    static final int MEDIUM_KICK_ROOT_Y = 232;
    static final int MEDIUM_KICK_FRAME_COUNT = 14;

    static final int RISE_SET_FRAME_WIDTH = 192;
    static final int RISE_SET_FRAME_HEIGHT = 238;
    static final int RISE_SET_ROOT_X = 100;
    static final int RISE_SET_ROOT_Y = 228;
    static final int RISE_SET_FRAME_COUNT = 6;

    static final int SPECIAL_S2_SET_FRAME_WIDTH = 244;
    static final int SPECIAL_S2_SET_FRAME_HEIGHT = 360;
    static final int SPECIAL_S2_SET_ROOT_X = 132;
    static final int SPECIAL_S2_SET_ROOT_Y = 349;
    static final int SPECIAL_S2_SET_FRAME_COUNT = 20;

    static final int SPECIAL_S3_SET_FRAME_WIDTH = 264;
    static final int SPECIAL_S3_SET_FRAME_HEIGHT = 250;
    static final int SPECIAL_S3_SET_ROOT_X = 117;
    static final int SPECIAL_S3_SET_ROOT_Y = 238;
    static final int SPECIAL_S3_SET_FRAME_COUNT = 21;

    static final int SPECIAL_S4_SET_FRAME_WIDTH = 288;
    static final int SPECIAL_S4_SET_FRAME_HEIGHT = 297;
    static final int SPECIAL_S4_SET_ROOT_X = 92;
    static final int SPECIAL_S4_SET_ROOT_Y = 284;
    static final int SPECIAL_S4_SET_FRAME_COUNT = 20;

    static final int SUPER_SET_FRAME_WIDTH = 225;
    static final int SUPER_SET_FRAME_HEIGHT = 250;
    static final int SUPER_SET_ROOT_X = 100;
    static final int SUPER_SET_ROOT_Y = 235;
    static final int SUPER_SET_FRAME_COUNT = 22;

    static final int TAUNT_FRAME_WIDTH = 234;
    static final int TAUNT_FRAME_HEIGHT = 281;
    static final int TAUNT_ROOT_X = 104;
    static final int TAUNT_ROOT_Y = 268;
    static final int TAUNT_FRAME_COUNT = 33;

    static final int THROW_SET_FRAME_WIDTH = 337;
    static final int THROW_SET_FRAME_HEIGHT = 244;
    static final int THROW_SET_ROOT_X = 135;
    static final int THROW_SET_ROOT_Y = 233;
    static final int THROW_SET_FRAME_COUNT = 9;

    static final int ULTRA_BEAM_FRAME_WIDTH = 274;
    static final int ULTRA_BEAM_FRAME_HEIGHT = 251;
    static final int ULTRA_BEAM_ROOT_X = 130;
    static final int ULTRA_BEAM_ROOT_Y = 236;
    static final int ULTRA_BEAM_FRAME_COUNT = 9;

    static final int VICTORY_FRAME_WIDTH = 170;
    static final int VICTORY_FRAME_HEIGHT = 296;
    static final int VICTORY_ROOT_X = 89;
    static final int VICTORY_ROOT_Y = 282;
    static final int VICTORY_FRAME_COUNT = 33;

    static final int WALK_BACK_SET_FRAME_WIDTH = 171;
    static final int WALK_BACK_SET_FRAME_HEIGHT = 247;
    static final int WALK_BACK_SET_ROOT_X = 86;
    static final int WALK_BACK_SET_ROOT_Y = 236;
    static final int WALK_BACK_SET_FRAME_COUNT = 17;

    static final int WALK_FORWARD_SET_FRAME_WIDTH = 182;
    static final int WALK_FORWARD_SET_FRAME_HEIGHT = 248;
    static final int WALK_FORWARD_SET_ROOT_X = 96;
    static final int WALK_FORWARD_SET_ROOT_Y = 237;
    static final int WALK_FORWARD_SET_FRAME_COUNT = 20;

    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_WIDTH = 232;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_HEIGHT = 239;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_X = 105;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_Y = 230;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_COUNT = 9;

    static final int PLAYER_TWO_IDLE_FRAME_WIDTH = 170;
    static final int PLAYER_TWO_IDLE_FRAME_HEIGHT = 244;
    static final int PLAYER_TWO_IDLE_ROOT_X = 85;
    static final int PLAYER_TWO_IDLE_ROOT_Y = 235;
    static final int PLAYER_TWO_IDLE_FRAME_COUNT = 8;

    static final int PLAYER_TWO_JAB_FRAME_WIDTH = 242;
    static final int PLAYER_TWO_JAB_FRAME_HEIGHT = 238;
    static final int PLAYER_TWO_JAB_ROOT_X = 108;
    static final int PLAYER_TWO_JAB_ROOT_Y = 229;
    static final int PLAYER_TWO_JAB_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_WIDTH = 314;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_HEIGHT = 246;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_X = 94;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_Y = 237;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MOVEMENT_FRAME_WIDTH = 244;
    static final int PLAYER_TWO_MOVEMENT_FRAME_HEIGHT = 244;
    static final int PLAYER_TWO_MOVEMENT_ROOT_X = 120;
    static final int PLAYER_TWO_MOVEMENT_ROOT_Y = 235;
    static final int PLAYER_TWO_MOVEMENT_FRAME_COUNT = 16;

}
