package com.gamelutagpt;
import java.util.*;
/** Generated by build_characters.py. Edit character packs, not this file. */
final class GeneratedCharacters {
 static final String[] TEAM = new String[]{"player_base","player_two"};
 static final String OPPONENT = "monster_npc";
 private static final Map<String,CharacterDefinition> ALL = build();
 static CharacterDefinition get(String id) { CharacterDefinition c=ALL.get(id); if(c==null)throw new IllegalArgumentException(id);return c; }
 static CharacterDefinition defaultCharacter() { return get("player_base"); }
 static CharacterDefinition opponentCharacter() { return get(OPPONENT); }
 private static Map<String,CharacterDefinition> build() {
 Map<String,CharacterDefinition> all=new LinkedHashMap<>();
 {
 Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Animation> s=new LinkedHashMap<>();
 a.put("IDLE",new CharacterDefinition.Animation("IDLE",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{0,1,2,3},new float[]{0.13000000f,0.13000000f,0.13000000f,0.13000000f},true,0.00000000f));
 a.put("COMBAT",new CharacterDefinition.Animation("COMBAT",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{0},new float[]{0.10000000f},false,0.00000000f));
 a.put("WALK_FORWARD",new CharacterDefinition.Animation("WALK_FORWARD",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{4,5,6,7},new float[]{},true,34.00000000f));
 a.put("WALK_BACK",new CharacterDefinition.Animation("WALK_BACK",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{7,6,5,4},new float[]{},true,32.00000000f));
 a.put("CROUCH",new CharacterDefinition.Animation("CROUCH",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8},new float[]{0.10000000f},false,0.00000000f));
 a.put("RISE",new CharacterDefinition.Animation("RISE",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{15,0},new float[]{0.07000000f,0.09000000f},false,0.00000000f));
 a.put("JUMP",new CharacterDefinition.Animation("JUMP",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{4,5,6},new float[]{0.08500000f,0.08500000f,0.11000000f},false,0.00000000f));
 a.put("FALL",new CharacterDefinition.Animation("FALL",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{11},new float[]{0.10000000f},false,0.00000000f));
 a.put("DASH",new CharacterDefinition.Animation("DASH",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{5,6,7},new float[]{},true,38.00000000f));
 a.put("BACKDASH",new CharacterDefinition.Animation("BACKDASH",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{7,6,5},new float[]{0.07000000f,0.07000000f,0.08000000f},false,0.00000000f));
 a.put("LAND",new CharacterDefinition.Animation("LAND",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,15},new float[]{0.07000000f,0.09000000f},false,0.00000000f));
 a.put("LIGHT_CLAW",new CharacterDefinition.Animation("LIGHT_CLAW",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,9,8},new float[]{0.04000000f,0.06000000f,0.06000000f},false,0.00000000f));
 a.put("MEDIUM_SWIPE",new CharacterDefinition.Animation("MEDIUM_SWIPE",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,10,9,8},new float[]{0.05000000f,0.07000000f,0.07000000f,0.07000000f},false,0.00000000f));
 a.put("HEAVY_SMASH",new CharacterDefinition.Animation("HEAVY_SMASH",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,10,11,12},new float[]{0.08000000f,0.10000000f,0.10000000f,0.12000000f},false,0.00000000f));
 a.put("ROAR",new CharacterDefinition.Animation("ROAR",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{13,14,13,15},new float[]{0.10000000f,0.14000000f,0.12000000f,0.10000000f},false,0.00000000f));
 a.put("LOW_CLAW",new CharacterDefinition.Animation("LOW_CLAW",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,11,8},new float[]{0.05000000f,0.07000000f,0.04000000f},false,0.00000000f));
 a.put("LOW_LUNGE",new CharacterDefinition.Animation("LOW_LUNGE",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,11,12},new float[]{0.07000000f,0.10000000f,0.09000000f},false,0.00000000f));
 a.put("RISING_SMASH",new CharacterDefinition.Animation("RISING_SMASH",new CharacterDefinition.Atlas("monster_npc_pack",256,231,128,223,4,16),new int[]{8,10,9,15},new float[]{0.10000000f,0.10000000f,0.10000000f,0.10000000f},false,0.00000000f));
 m.put("L",new CharacterDefinition.Move("L",a.get("LIGHT_CLAW"),null,300,0.16000000f,0.04000000f,0.09500000f,111.00000000f,78.00000000f));
 m.put("M",new CharacterDefinition.Move("M",a.get("MEDIUM_SWIPE"),null,500,0.26000000f,0.07000000f,0.18000000f,131.00000000f,78.00000000f));
 m.put("H",new CharacterDefinition.Move("H",a.get("HEAVY_SMASH"),null,800,0.40000000f,0.16000000f,0.28000000f,161.00000000f,78.00000000f));
 m.put("2L",new CharacterDefinition.Move("2L",a.get("LOW_CLAW"),null,300,0.16000000f,0.05800000f,0.10200000f,84.00000000f,42.00000000f));
 m.put("2M",new CharacterDefinition.Move("2M",a.get("LOW_LUNGE"),null,500,0.26000000f,0.09400000f,0.16600000f,116.00000000f,42.00000000f));
 m.put("2H",new CharacterDefinition.Move("2H",a.get("RISING_SMASH"),null,800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,42.00000000f));
 m.put("jL",new CharacterDefinition.Move("jL",null,"AIR",300,0.16000000f,0.05800000f,0.10200000f,84.00000000f,78.00000000f));
 m.put("jM",new CharacterDefinition.Move("jM",null,"AIR",500,0.26000000f,0.09400000f,0.16600000f,116.00000000f,78.00000000f));
 m.put("jH",new CharacterDefinition.Move("jH",null,"AIR",800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,78.00000000f));
 s.put("S",a.get("ROAR"));
 s.put("SUPER",a.get("ROAR"));
 all.put("monster_npc",new CharacterDefinition("monster_npc","Brutamonte",new CharacterVisualProfile("monster_npc",256,256,128.00000000f,248.00000000f,1.40000000f),1,295.40000000f,247.80000000f,new CharacterDefinition.Fighter(0xFFD9485F,10000,new String[]{},new CharacterDefinition.Projectile(650,560.00000000f,980.00000000f,100.00000000f,110.00000000f,90.00000000f,110.00000000f),new int[]{5,1},new CharacterDefinition.Projectile(2850,1320.00000000f,1280.00000000f,120.00000000f,115.00000000f,115.00000000f,115.00000000f),new CharacterDefinition.Body(78.00000000f,290.00000000f,240.00000000f,64.00000000f,130.00000000f)),a,m,s));
 }
 {
 Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Animation> s=new LinkedHashMap<>();
 a.put("IDLE",new CharacterDefinition.Animation("IDLE",new CharacterDefinition.Atlas("player_base_idle",190,244,95,234,4,8),new int[]{0,1,2,3,4,5,6,7},new float[]{0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f},true,0.00000000f));
 a.put("COMBAT",new CharacterDefinition.Animation("COMBAT",new CharacterDefinition.Atlas("player_base_idle",190,244,95,234,4,8),new int[]{0},new float[]{0.10000000f},false,0.00000000f));
 a.put("WALK_FORWARD",new CharacterDefinition.Animation("WALK_FORWARD",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{0,1,2,3},new float[]{},true,36.00000000f));
 a.put("WALK_BACK",new CharacterDefinition.Animation("WALK_BACK",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{4,5,6,7},new float[]{},true,32.00000000f));
 a.put("CROUCH",new CharacterDefinition.Animation("CROUCH",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{8,9},new float[]{0.07500000f,0.10000000f},false,0.00000000f));
 a.put("RISE",new CharacterDefinition.Animation("RISE",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{8},new float[]{0.07500000f},false,0.00000000f));
 a.put("JUMP",new CharacterDefinition.Animation("JUMP",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{10},new float[]{0.10000000f},false,0.00000000f));
 a.put("FALL",new CharacterDefinition.Animation("FALL",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{11},new float[]{0.10000000f},false,0.00000000f));
 a.put("DASH",new CharacterDefinition.Animation("DASH",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{12,13},new float[]{0.10000000f,0.10000000f},true,0.00000000f));
 a.put("BACKDASH",new CharacterDefinition.Animation("BACKDASH",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{14},new float[]{0.20000000f},false,0.00000000f));
 a.put("LAND",new CharacterDefinition.Animation("LAND",new CharacterDefinition.Atlas("player_base_movement",253,229,125,220,4,16),new int[]{15},new float[]{0.10000000f},false,0.00000000f));
 a.put("LIGHT_JAB",new CharacterDefinition.Animation("LIGHT_JAB",new CharacterDefinition.Atlas("player_base_jab",224,227,112,218,3,3),new int[]{0,1,2},new float[]{0.04000000f,0.06000000f,0.06000000f},false,0.00000000f));
 a.put("MEDIUM_KICK",new CharacterDefinition.Animation("MEDIUM_KICK",new CharacterDefinition.Atlas("player_base_medium_kick",327,245,94,236,3,3),new int[]{0,1,2},new float[]{0.07000000f,0.10000000f,0.09000000f},false,0.00000000f));
 a.put("HEAVY_STRAIGHT",new CharacterDefinition.Animation("HEAVY_STRAIGHT",new CharacterDefinition.Atlas("player_base_heavy_straight",282,225,120,216,9,9),new int[]{0,1,2,3,4,5,6,7,8},new float[]{0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.05000000f,0.05000000f,0.05000000f,0.05000000f},false,0.00000000f));
 a.put("DEFENSE_STAND",new CharacterDefinition.Animation("DEFENSE_STAND",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{0},new float[]{0.18000000f},false,0.00000000f));
 a.put("DEFENSE_CROUCH",new CharacterDefinition.Animation("DEFENSE_CROUCH",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{1},new float[]{0.18000000f},false,0.00000000f));
 a.put("HIT_STAND",new CharacterDefinition.Animation("HIT_STAND",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{2},new float[]{0.22000000f},false,0.00000000f));
 a.put("HIT_CROUCH",new CharacterDefinition.Animation("HIT_CROUCH",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{3},new float[]{0.22000000f},false,0.00000000f));
 a.put("HIT_AIR",new CharacterDefinition.Animation("HIT_AIR",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{4},new float[]{0.22000000f},false,0.00000000f));
 a.put("KNOCKDOWN",new CharacterDefinition.Animation("KNOCKDOWN",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{5},new float[]{0.22000000f},false,0.00000000f));
 a.put("GROUNDED",new CharacterDefinition.Animation("GROUNDED",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{6},new float[]{1.20000000f},false,0.00000000f));
 a.put("GETUP",new CharacterDefinition.Animation("GETUP",new CharacterDefinition.Atlas("player_base_missing",236,170,118,162,14,14),new int[]{7},new float[]{0.35000000f},false,0.00000000f));
 a.put("CROUCH_LIGHT",new CharacterDefinition.Animation("CROUCH_LIGHT",new CharacterDefinition.Atlas("player_base_crouch_light",215,186,88,177,4,4),new int[]{0,1,2,3},new float[]{0.03000000f,0.04000000f,0.04000000f,0.05000000f},false,0.00000000f));
 a.put("CROUCH_MEDIUM",new CharacterDefinition.Animation("CROUCH_MEDIUM",new CharacterDefinition.Atlas("player_base_crouch_medium",330,187,126,178,4,4),new int[]{0,1,2,3},new float[]{0.05000000f,0.05000000f,0.07000000f,0.09000000f},false,0.00000000f));
 a.put("CROUCH_HEAVY",new CharacterDefinition.Animation("CROUCH_HEAVY",new CharacterDefinition.Atlas("player_base_crouch_heavy",219,282,106,273,4,4),new int[]{0,1,2,3},new float[]{0.07000000f,0.07000000f,0.13000000f,0.13000000f},false,0.00000000f));
 m.put("L",new CharacterDefinition.Move("L",a.get("LIGHT_JAB"),null,300,0.16000000f,0.04000000f,0.10000000f,84.00000000f,78.00000000f));
 m.put("M",new CharacterDefinition.Move("M",a.get("MEDIUM_KICK"),null,500,0.26000000f,0.07000000f,0.17000000f,116.00000000f,78.00000000f));
 m.put("H",new CharacterDefinition.Move("H",a.get("HEAVY_STRAIGHT"),null,800,0.40000000f,0.16000000f,0.25000000f,148.00000000f,78.00000000f));
 m.put("2L",new CharacterDefinition.Move("2L",a.get("CROUCH_LIGHT"),null,300,0.16000000f,0.04000000f,0.10000000f,84.00000000f,42.00000000f));
 m.put("2M",new CharacterDefinition.Move("2M",a.get("CROUCH_MEDIUM"),null,500,0.26000000f,0.10000000f,0.17000000f,116.00000000f,42.00000000f));
 m.put("2H",new CharacterDefinition.Move("2H",a.get("CROUCH_HEAVY"),null,800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,42.00000000f));
 m.put("jL",new CharacterDefinition.Move("jL",null,"AIR",300,0.16000000f,0.05800000f,0.10200000f,84.00000000f,78.00000000f));
 m.put("jM",new CharacterDefinition.Move("jM",null,"AIR",500,0.26000000f,0.09400000f,0.16600000f,116.00000000f,78.00000000f));
 m.put("jH",new CharacterDefinition.Move("jH",null,"AIR",800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,78.00000000f));
 all.put("player_base",new CharacterDefinition("player_base","Lutador base",new CharacterVisualProfile("player_base",256,256,128.00000000f,238.00000000f,1.00000000f),1,226.00000000f,168.00000000f,new CharacterDefinition.Fighter(0xFFF4B73B,10000,new String[]{"L","M","H"},new CharacterDefinition.Projectile(850,720.00000000f,760.00000000f,62.00000000f,82.00000000f,65.00000000f,82.00000000f),new int[]{3,1},new CharacterDefinition.Projectile(3200,1450.00000000f,1180.00000000f,78.00000000f,86.00000000f,86.00000000f,82.00000000f),new CharacterDefinition.Body(34.00000000f,145.00000000f,90.00000000f,30.00000000f,120.00000000f)),a,m,s));
 }
 {
 Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Animation> s=new LinkedHashMap<>();
 a.put("IDLE",new CharacterDefinition.Animation("IDLE",new CharacterDefinition.Atlas("player_two_idle",170,244,85,235,4,8),new int[]{0,1,2,3,4,5,6,7},new float[]{0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f},true,0.00000000f));
 a.put("COMBAT",new CharacterDefinition.Animation("COMBAT",new CharacterDefinition.Atlas("player_two_idle",170,244,85,235,4,8),new int[]{0},new float[]{0.10000000f},false,0.00000000f));
 a.put("WALK_FORWARD",new CharacterDefinition.Animation("WALK_FORWARD",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{0,1,2,3},new float[]{},true,36.00000000f));
 a.put("WALK_BACK",new CharacterDefinition.Animation("WALK_BACK",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{4,5,6,7},new float[]{},true,32.00000000f));
 a.put("CROUCH",new CharacterDefinition.Animation("CROUCH",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{8,9},new float[]{0.07500000f,0.10000000f},false,0.00000000f));
 a.put("RISE",new CharacterDefinition.Animation("RISE",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{8},new float[]{0.07500000f},false,0.00000000f));
 a.put("JUMP",new CharacterDefinition.Animation("JUMP",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{10,11,12},new float[]{0.08000000f,0.08000000f,0.10000000f},false,0.00000000f));
 a.put("FALL",new CharacterDefinition.Animation("FALL",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{13},new float[]{0.10000000f},false,0.00000000f));
 a.put("DASH",new CharacterDefinition.Animation("DASH",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{14},new float[]{},true,36.00000000f));
 a.put("BACKDASH",new CharacterDefinition.Animation("BACKDASH",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{15},new float[]{0.20000000f},false,0.00000000f));
 a.put("LAND",new CharacterDefinition.Animation("LAND",new CharacterDefinition.Atlas("player_two_movement",359,244,180,235,4,16),new int[]{8},new float[]{0.10000000f},false,0.00000000f));
 a.put("LIGHT_JAB",new CharacterDefinition.Animation("LIGHT_JAB",new CharacterDefinition.Atlas("player_two_jab",242,238,108,229,3,3),new int[]{0,1,2},new float[]{0.04000000f,0.06000000f,0.06000000f},false,0.00000000f));
 a.put("MEDIUM_KICK",new CharacterDefinition.Animation("MEDIUM_KICK",new CharacterDefinition.Atlas("player_two_medium_kick",314,246,94,237,3,3),new int[]{0,1,2},new float[]{0.07000000f,0.10000000f,0.09000000f},false,0.00000000f));
 a.put("HEAVY_STRAIGHT",new CharacterDefinition.Animation("HEAVY_STRAIGHT",new CharacterDefinition.Atlas("player_two_heavy_straight",283,239,105,230,9,9),new int[]{0,1,2,3,4,5,6,7,8},new float[]{0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.05000000f,0.05000000f,0.05000000f,0.05000000f},false,0.00000000f));
 m.put("L",new CharacterDefinition.Move("L",a.get("LIGHT_JAB"),null,300,0.16000000f,0.04000000f,0.10000000f,84.00000000f,78.00000000f));
 m.put("M",new CharacterDefinition.Move("M",a.get("MEDIUM_KICK"),null,500,0.26000000f,0.07000000f,0.17000000f,116.00000000f,78.00000000f));
 m.put("H",new CharacterDefinition.Move("H",a.get("HEAVY_STRAIGHT"),null,800,0.40000000f,0.16000000f,0.25000000f,148.00000000f,78.00000000f));
 m.put("2L",new CharacterDefinition.Move("2L",null,"CROUCH",300,0.16000000f,0.05800000f,0.10200000f,84.00000000f,42.00000000f));
 m.put("2M",new CharacterDefinition.Move("2M",null,"CROUCH",500,0.26000000f,0.09400000f,0.16600000f,116.00000000f,42.00000000f));
 m.put("2H",new CharacterDefinition.Move("2H",null,"CROUCH",800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,42.00000000f));
 m.put("jL",new CharacterDefinition.Move("jL",null,"AIR",300,0.16000000f,0.05800000f,0.10200000f,84.00000000f,78.00000000f));
 m.put("jM",new CharacterDefinition.Move("jM",null,"AIR",500,0.26000000f,0.09400000f,0.16600000f,116.00000000f,78.00000000f));
 m.put("jH",new CharacterDefinition.Move("jH",null,"AIR",800,0.40000000f,0.14400000f,0.25600000f,148.00000000f,78.00000000f));
 all.put("player_two",new CharacterDefinition("player_two","Lutador Teste 2",new CharacterVisualProfile("player_two",384,256,192.00000000f,246.00000000f,1.00000000f),1,227.00000000f,151.00000000f,new CharacterDefinition.Fighter(0xFF4ACDE8,10000,new String[]{"L","L","H","M"},new CharacterDefinition.Projectile(650,560.00000000f,980.00000000f,62.00000000f,82.00000000f,65.00000000f,82.00000000f),new int[]{5,1},new CharacterDefinition.Projectile(2850,1320.00000000f,1280.00000000f,78.00000000f,86.00000000f,86.00000000f,82.00000000f),new CharacterDefinition.Body(34.00000000f,145.00000000f,90.00000000f,30.00000000f,120.00000000f)),a,m,s));
 }
 return Collections.unmodifiableMap(all);
 }
}
