package com.gamelutagpt;

/** Generated by tools/sprites/import_sprites.py. Do not edit by hand. */
final class GeneratedSpriteLayouts {
    private GeneratedSpriteLayouts() {}

    static final int MONSTER_NPC_PACK_FRAME_WIDTH = 32;
    static final int MONSTER_NPC_PACK_FRAME_HEIGHT = 32;
    static final int MONSTER_NPC_PACK_ROOT_X = 16;
    static final int MONSTER_NPC_PACK_ROOT_Y = 31;
    static final int MONSTER_NPC_PACK_FRAME_COUNT = 8;

    static final int HEAVY_STRAIGHT_FRAME_WIDTH = 320;
    static final int HEAVY_STRAIGHT_FRAME_HEIGHT = 256;
    static final int HEAVY_STRAIGHT_ROOT_X = 128;
    static final int HEAVY_STRAIGHT_ROOT_Y = 238;
    static final int HEAVY_STRAIGHT_FRAME_COUNT = 9;

    static final int IDLE_FRAME_WIDTH = 256;
    static final int IDLE_FRAME_HEIGHT = 256;
    static final int IDLE_ROOT_X = 128;
    static final int IDLE_ROOT_Y = 238;
    static final int IDLE_FRAME_COUNT = 8;

    static final int JAB_FRAME_WIDTH = 256;
    static final int JAB_FRAME_HEIGHT = 256;
    static final int JAB_ROOT_X = 128;
    static final int JAB_ROOT_Y = 238;
    static final int JAB_FRAME_COUNT = 3;

    static final int MEDIUM_KICK_FRAME_WIDTH = 384;
    static final int MEDIUM_KICK_FRAME_HEIGHT = 256;
    static final int MEDIUM_KICK_ROOT_X = 128;
    static final int MEDIUM_KICK_ROOT_Y = 238;
    static final int MEDIUM_KICK_FRAME_COUNT = 3;

    static final int MOVEMENT_FRAME_WIDTH = 256;
    static final int MOVEMENT_FRAME_HEIGHT = 256;
    static final int MOVEMENT_ROOT_X = 128;
    static final int MOVEMENT_ROOT_Y = 238;
    static final int MOVEMENT_FRAME_COUNT = 16;

    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_WIDTH = 384;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_HEIGHT = 256;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_X = 192;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_ROOT_Y = 246;
    static final int PLAYER_TWO_HEAVY_STRAIGHT_FRAME_COUNT = 9;

    static final int PLAYER_TWO_IDLE_FRAME_WIDTH = 384;
    static final int PLAYER_TWO_IDLE_FRAME_HEIGHT = 256;
    static final int PLAYER_TWO_IDLE_ROOT_X = 192;
    static final int PLAYER_TWO_IDLE_ROOT_Y = 246;
    static final int PLAYER_TWO_IDLE_FRAME_COUNT = 8;

    static final int PLAYER_TWO_JAB_FRAME_WIDTH = 384;
    static final int PLAYER_TWO_JAB_FRAME_HEIGHT = 256;
    static final int PLAYER_TWO_JAB_ROOT_X = 192;
    static final int PLAYER_TWO_JAB_ROOT_Y = 246;
    static final int PLAYER_TWO_JAB_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_WIDTH = 448;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_HEIGHT = 256;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_X = 192;
    static final int PLAYER_TWO_MEDIUM_KICK_ROOT_Y = 246;
    static final int PLAYER_TWO_MEDIUM_KICK_FRAME_COUNT = 3;

    static final int PLAYER_TWO_MOVEMENT_FRAME_WIDTH = 384;
    static final int PLAYER_TWO_MOVEMENT_FRAME_HEIGHT = 256;
    static final int PLAYER_TWO_MOVEMENT_ROOT_X = 192;
    static final int PLAYER_TWO_MOVEMENT_ROOT_Y = 246;
    static final int PLAYER_TWO_MOVEMENT_FRAME_COUNT = 16;

}
