package com.gamelutagpt;
import java.util.*;
/** Generated by build_characters.py. Edit character packs, not this file. */
final class GeneratedCharacters {
 static final String[] TEAM = new String[]{"player_base","player_two"};
 private static final Map<String,CharacterDefinition> ALL = build();
 static CharacterDefinition get(String id) { CharacterDefinition c=ALL.get(id); if(c==null)throw new IllegalArgumentException(id);return c; }
 static CharacterDefinition defaultCharacter() { return get("player_base"); }
 private static Map<String,CharacterDefinition> build() {
 Map<String,CharacterDefinition> all=new LinkedHashMap<>();
 {
 Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();
 a.put("IDLE",new CharacterDefinition.Animation("IDLE",new CharacterDefinition.Atlas("player_base_idle",256,256,128,238,4,8),new int[]{0,1,2,3,4,5,6,7},new float[]{0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f},true,0.00000000f));
 a.put("COMBAT",new CharacterDefinition.Animation("COMBAT",new CharacterDefinition.Atlas("player_base_idle",256,256,128,238,4,8),new int[]{0},new float[]{0.10000000f},false,0.00000000f));
 a.put("WALK_FORWARD",new CharacterDefinition.Animation("WALK_FORWARD",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{0,1,2,3},new float[]{},true,36.00000000f));
 a.put("WALK_BACK",new CharacterDefinition.Animation("WALK_BACK",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{4,5,6,7},new float[]{},true,32.00000000f));
 a.put("CROUCH",new CharacterDefinition.Animation("CROUCH",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{8,9},new float[]{0.07500000f,0.10000000f},false,0.00000000f));
 a.put("RISE",new CharacterDefinition.Animation("RISE",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{8},new float[]{0.07500000f},false,0.00000000f));
 a.put("JUMP",new CharacterDefinition.Animation("JUMP",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{10},new float[]{0.10000000f},false,0.00000000f));
 a.put("FALL",new CharacterDefinition.Animation("FALL",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{11},new float[]{0.10000000f},false,0.00000000f));
 a.put("DASH",new CharacterDefinition.Animation("DASH",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{12,13},new float[]{0.10000000f,0.10000000f},true,0.00000000f));
 a.put("BACKDASH",new CharacterDefinition.Animation("BACKDASH",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{14},new float[]{0.20000000f},false,0.00000000f));
 a.put("LAND",new CharacterDefinition.Animation("LAND",new CharacterDefinition.Atlas("player_base_movement",256,256,128,238,4,16),new int[]{15},new float[]{0.10000000f},false,0.00000000f));
 a.put("LIGHT_JAB",new CharacterDefinition.Animation("LIGHT_JAB",new CharacterDefinition.Atlas("player_base_jab",256,256,128,238,3,3),new int[]{0,1,2},new float[]{0.04000000f,0.06000000f,0.06000000f},false,0.00000000f));
 a.put("MEDIUM_KICK",new CharacterDefinition.Animation("MEDIUM_KICK",new CharacterDefinition.Atlas("player_base_medium_kick",384,256,128,238,3,3),new int[]{0,1,2},new float[]{0.07000000f,0.10000000f,0.09000000f},false,0.00000000f));
 a.put("HEAVY_STRAIGHT",new CharacterDefinition.Animation("HEAVY_STRAIGHT",new CharacterDefinition.Atlas("player_base_heavy_straight",320,256,128,238,9,9),new int[]{0,1,2,3,4,5,6,7,8},new float[]{0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.05000000f,0.05000000f,0.05000000f,0.05000000f},false,0.00000000f));
 m.put("L",new CharacterDefinition.Move(a.get("LIGHT_JAB"),300,0.04000000f,0.10000000f,118.00000000f));
 m.put("M",new CharacterDefinition.Move(a.get("MEDIUM_KICK"),500,0.07000000f,0.17000000f,150.00000000f));
 m.put("H",new CharacterDefinition.Move(a.get("HEAVY_STRAIGHT"),800,0.16000000f,0.25000000f,182.00000000f));
 all.put("player_base",new CharacterDefinition("player_base","Lutador base",new CharacterVisualProfile("player_base",256,256,128.00000000f,238.00000000f,1.00000000f),a,m));
 }
 {
 Map<String,CharacterDefinition.Animation> a=new LinkedHashMap<>();
 Map<String,CharacterDefinition.Move> m=new LinkedHashMap<>();
 a.put("IDLE",new CharacterDefinition.Animation("IDLE",new CharacterDefinition.Atlas("player_two_idle",384,256,192,246,4,8),new int[]{0,1,2,3,4,5,6,7},new float[]{0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f,0.12000000f},true,0.00000000f));
 a.put("COMBAT",new CharacterDefinition.Animation("COMBAT",new CharacterDefinition.Atlas("player_two_idle",384,256,192,246,4,8),new int[]{0},new float[]{0.10000000f},false,0.00000000f));
 a.put("WALK_FORWARD",new CharacterDefinition.Animation("WALK_FORWARD",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{0,1,2,3},new float[]{},true,36.00000000f));
 a.put("WALK_BACK",new CharacterDefinition.Animation("WALK_BACK",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{4,5,6,7},new float[]{},true,32.00000000f));
 a.put("CROUCH",new CharacterDefinition.Animation("CROUCH",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{8,9},new float[]{0.07500000f,0.10000000f},false,0.00000000f));
 a.put("RISE",new CharacterDefinition.Animation("RISE",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{8},new float[]{0.07500000f},false,0.00000000f));
 a.put("JUMP",new CharacterDefinition.Animation("JUMP",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{10,11,12},new float[]{0.08000000f,0.08000000f,0.10000000f},false,0.00000000f));
 a.put("FALL",new CharacterDefinition.Animation("FALL",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{13},new float[]{0.10000000f},false,0.00000000f));
 a.put("DASH",new CharacterDefinition.Animation("DASH",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{14},new float[]{},true,36.00000000f));
 a.put("BACKDASH",new CharacterDefinition.Animation("BACKDASH",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{15},new float[]{0.20000000f},false,0.00000000f));
 a.put("LAND",new CharacterDefinition.Animation("LAND",new CharacterDefinition.Atlas("player_two_movement",384,256,192,246,4,16),new int[]{8},new float[]{0.10000000f},false,0.00000000f));
 a.put("LIGHT_JAB",new CharacterDefinition.Animation("LIGHT_JAB",new CharacterDefinition.Atlas("player_two_jab",384,256,192,246,3,3),new int[]{0,1,2},new float[]{0.04000000f,0.06000000f,0.06000000f},false,0.00000000f));
 a.put("MEDIUM_KICK",new CharacterDefinition.Animation("MEDIUM_KICK",new CharacterDefinition.Atlas("player_two_medium_kick",448,256,192,246,3,3),new int[]{0,1,2},new float[]{0.07000000f,0.10000000f,0.09000000f},false,0.00000000f));
 a.put("HEAVY_STRAIGHT",new CharacterDefinition.Animation("HEAVY_STRAIGHT",new CharacterDefinition.Atlas("player_two_heavy_straight",384,256,192,246,9,9),new int[]{0,1,2,3,4,5,6,7,8},new float[]{0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.04000000f,0.05000000f,0.05000000f,0.05000000f,0.05000000f},false,0.00000000f));
 m.put("L",new CharacterDefinition.Move(a.get("LIGHT_JAB"),300,0.04000000f,0.10000000f,118.00000000f));
 m.put("M",new CharacterDefinition.Move(a.get("MEDIUM_KICK"),500,0.07000000f,0.17000000f,150.00000000f));
 m.put("H",new CharacterDefinition.Move(a.get("HEAVY_STRAIGHT"),800,0.16000000f,0.25000000f,182.00000000f));
 all.put("player_two",new CharacterDefinition("player_two","Lutador Teste 2",new CharacterVisualProfile("player_two",384,256,192.00000000f,246.00000000f,1.00000000f),a,m));
 }
 return Collections.unmodifiableMap(all);
 }
}
