package com.gamelutagpt;
/** Generated by build_characters.py from its state vocabulary. Do not edit. */
final class SpriteStates {
 private SpriteStates() {}
 static final String IDLE = "IDLE";
 static final String COMBAT = "COMBAT";
 static final String WALK_FORWARD = "WALK_FORWARD";
 static final String WALK_BACK = "WALK_BACK";
 static final String CROUCH = "CROUCH";
 static final String RISE = "RISE";
 static final String JUMP = "JUMP";
 static final String FALL = "FALL";
 static final String DASH = "DASH";
 static final String BACKDASH = "BACKDASH";
 static final String LAND = "LAND";
 static final String DEFENSE_STAND = "DEFENSE_STAND";
 static final String DEFENSE_CROUCH = "DEFENSE_CROUCH";
 static final String DEFENSE_AIR = "DEFENSE_AIR";
 static final String HIT_STAND = "HIT_STAND";
 static final String HIT_CROUCH = "HIT_CROUCH";
 static final String HIT_AIR = "HIT_AIR";
 static final String KNOCKDOWN = "KNOCKDOWN";
 static final String GROUNDED = "GROUNDED";
 static final String GETUP = "GETUP";
 static final String THROW_GRAB = "THROW_GRAB";
 static final String THROW_TOSS = "THROW_TOSS";
 static final String POSE_CROUCH = "CROUCH";
 static final String POSE_AIR = "AIR";
}
