plugins { id 'java-library' }

// Motor de cenário com falso 3D, em Java puro: roda igual no Android e no PC.
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    api project(':render-core')
    testImplementation 'junit:junit:4.13.2'
}
